multiformats/rust-multihash

- Cargo.toml
Can you also release new version to crates.io?
Thanks :)
> updated tiny-keccak to 1.2

- Cargo.toml
> Update ring to 0.12

- src/errors.rs
- src/hashes.rs
Related: https://github.com/ipld/rust-cid/pull/10
> fix(spelling): UnkownCode -> UnknownCode

- .travis.yml
- run Clippy and Rustfmt
- remove code coverage as that didn't work recently anyway
> chore: update Travis CI configuration

- src/errors.rs
- src/hashes.rs
- src/lib.rs
- tests/lib.rs
* Add peer id inlining for small public keys
* Apply @twittner suggestions
* Restore hashing
Originally from https://github.com/libp2p/rust-libp2p/commit/c6e8e6328ae15de27df64249be9085965ecf96fe.
> Add identity hash

- src/digests.rs
This should be the last PR that integrates all changes that I wanted to port over from https://github.com/libp2p/rust-libp2p/tree/master/misc/multihash and https://github.com/multiformats/rust-multihash/pull/30.
> Misc improvements

- README.md
I dare to merge this one right away without further review as I'd like to do a release. A new release is better with an updated README.
> docs: update README to reflect current API

- src/digests.rs
- src/hashes.rs
- src/lib.rs
> Add MultihashHasher.

- src/hashes.rs
> feat: derive `PartialOrd`,`Ord` and `Hash` trait for `Code`

- Cargo.toml
> feat: update unsigned-varint to v0.4

- .github/codecov.yml
- .github/workflows/build.yml
- derive/src/multihash.rs
> chore: improve github actions

- .github/workflows/build.yml
- .gitignore
- derive/Cargo.toml
- derive/src/multihash.rs
- derive/src/utils.rs
Close #112 
Also close useless PRs (see dependabot/dependabot-core#3704):
Close #122 
Close #123 
Close #124 
Close #125 
Close #126
> Bump proc-macro-crate to v1.0.0

- Cargo.toml
- src/multihash.rs
waiting for #127 to be merged firstly
Close #118
> Bump parity scale codec to v2

- derive/src/multihash.rs
- src/hasher_impl.rs
- tests/lib.rs
> chore: fix clippy warings

- src/multihash_impl.rs
> feat: derive Serde (de)serialization for the default code table

- src/arb.rs
As we know that we won't need more more than S bytes to fill the buffer.
> [arb] make size_hint more precise

- Cargo.lock
- Cargo.toml
- examples/manual_mh.rs
- src/hasher_impl.rs
- src/lib.rs
- src/multihash_impl.rs
- tests/lib.rs
> Add ripemd family of hashes

- src/multihash.rs
> add `into_inner`

- Cargo.toml
> chore(deps): update serde-big-array to v0.5.1

- CHANGELOG.md
Adding the changelog entry for the 0.18.1 release.
> chore: add 0.18.1 to changelog

- codetable/Cargo.toml
> Switch sha-1 package name to sha1
