multiformats/rust-multihash

src/lib.rs

This lint was removed in nightly rust.  Note that while this lint still
exists in the Stable and Beta channels, it only applies if we have types
with `#[repr(C)]` that implement `Drop`.  Since this library has neither
(and will probably never have them), it is safe to remove this lint.

Remove the `drop_with_repr_extern` lint.

---

Cargo.toml
src/hashes.rs
src/lib.rs
tests/lib.rs

This commit makes an API change to the `encode`, `decode`, and
`MultiHash` functions/types, to operate on bytes, not strings.
In rust, all strings are valid UTF-8, and it's impossible to construct
one that's not.  With the previous API, only UTF-8 data could be hashed,
so the new API operates on bytes instead.
The other API change is for encode to return a Vec<u8> of bytes, instead
of a hex-encoded string.  The hex-encoded string was not incorrect, but
wasn't a nice as it could be, as it forced this particular encoding on
the user.
Other changes:
* No longer export the `hashes` module, since its contents are already
exported.
* Removed the rustc_serialized dependency.
* Made `to_hex` public, as it might be a useful utility function (and
removed some unnecessary calls to `.rev()`
Since …

Breaking API change: encode and decode bytes, not strings.

---

.gitignore
.travis.yml
Cargo.toml
README.md
src/hashes.rs
src/lib.rs
tests/lib.rs

feat: move to ring

---

Cargo.toml
README.md
src/hashes.rs

This commit updates the doc link to https://docs.rs/multihash, which will auto-update when new a new version is published to crates.io. Currently, the docs hosted on Github pages are out of date.
I also added a doc link to `Cargo.toml` so a documentation link shows up on crates.io.
Finally, I updated the README section and the doc comments about supported hash functions so they represent the current state of the code.

docs: fix some outdated links and descriptions

---

Cargo.toml

The crates.io page at https://crates.io/crates/multihash makes it look
like there's no public repository for the project. Improve this by
replacing the "homepage" link with a "repository" link.

Replace "homepage" link with "repository" link.

---

Cargo.toml

Before *ring* 0.9.3, it was possible to link multiple versions of *ring* into a program, e.g. if one version depended on *ring* 0.6 and another dependend on *ring* 0.9. Unfortunately, this doesn't work, because the linker doesn't know to how to link *ring*'s C/asm code correctly in that kind of situation. *ring* 0.9.3 added a flag to its Cargo.toml to tell the Rust toolchain to stop allowing multiple versions of *ring* to be linked into the same program, to prevent any problems this may cause.
*ring* 0.9.4 was released with an update to make some crates easier to update to 0.9.x.

0.6.0: Update to *ring* 0.9.4.

---

src/errors.rs
src/hashes.rs
src/lib.rs
tests/lib.rs

Clippy suggests to pass on small values by value instead of reference.
For example:
```
warning: this argument (1 byte) is passed by reference, but would be more efficient if passed by value (limit: 8 byte)
--> src/hashes.rs:38:17
|
38 |     pub fn code(&self) -> u8 {
|                 ^^^^^ help: consider passing by value instead: `self`
|
= note: `#[warn(clippy::trivially_copy_pass_by_ref)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#trivially_copy_pass_by_ref

Cargo fmt and Clippy

---

src/errors.rs
src/hashes.rs
src/lib.rs
tests/lib.rs

I start to backport changes from the multihash version rust-libp2p is using.
I go through all changes and create (hopefully sensible) PRs out of them. I cherry pick commits from the rust-libp2p version and make minimal changes to them (e.g. style or that they compile).
Then I base additional changes that I think make sense on top of those.
This PR is by far the one with the biggest changes, the subsequent PRs should be smaller.

rust-libp2p related changes part 1

---

Cargo.toml
src/hashes.rs
src/lib.rs
tests/lib.rs

PR ref: https://github.com/multiformats/rust-multihash/pull/39
Updates the blake2 dependencies per comment: https://github.com/multiformats/rust-multihash/pull/39#discussion_r346398065
Let me know if anything else needs to change as this would be nice to get in

blake2 support

---

src/lib.rs

This is another set of patches backported from libp2p's multihash library.

rust-libp2p related changes part 3

---

Cargo.toml
src/lib.rs

multihash: Use `Bytes` instead of `Vec<u8>` internally.
To improve the efficiency of cloning multi-hashes (e.g. as the
representation of `PeerId`s), this PR replaces the `Vec<u8>`
representation with `Bytes`. The API is kept backwards
compatible and does not leak the representation type.
Originally from https://github.com/libp2p/rust-libp2p/commit/8af4a28152d12110dce72128bbe19a34106b1d00.

multihash: Use `Bytes` instead of `Vec<u8>` internally. (#1187)

---

src/hashes.rs
src/lib.rs
tests/lib.rs

- Adds blake2b256 and blake2s128 generation with multihash. 
Would be ideal to be able to pass in the length of hash to these variable hashing functions but I didn't want to rewrite this whole library to support all possible hash lengths for blake hashes. I added support for the two hash lengths defined but not implemented (I needed blake2b256).

Add support for blake2b256 and blake2s128

---

Cargo.toml
src/lib.rs
src/storage.rs
tests/lib.rs

This also gets rid of the Bytes dependency and replaces it with an `Arc<[u8]>`.
Implementation for https://github.com/multiformats/rust-multihash/issues/46
Note that the size of this new multihash is 40, where as the size of the old Bytes based multihash is 32, plus the stuff on the heap. I think this is a pretty good tradeoff!

Use inline storage for small hashes

---

src/lib.rs

This is just lexicographical byte ordering, which should be very fast
in case of multihashes since they usually differ within the first 8 byte
word.
Ordering is useful to have if you e.g. want to output a set of multihashes
in a deterministic way for debugging/testing purposes. Also, many possible storage engines work using lexicographical byte ordering. And it allows you to use ordering based collections like BTreeSet with multihashes.
This is based on https://github.com/multiformats/rust-multihash/pull/47 , so should be reviewed once
that is merged.

Add ordering for Multihash and MultihashRef

---

Cargo.toml
src/arb.rs
src/lib.rs

Implements #48 
This is a request for discussion about if this way of providing arbitraries both for internal use and for use from other crates is a good way to go.
If somebody has a simpler way to achieve this I am eager to hear about it...
I verified that the dependencies are not in the output unless you build with the feature flag enabled. See https://github.com/rklaehn/rust-feature-experiment
This is based on https://github.com/multiformats/rust-multihash/pull/47 , so should be reviewed once that is merged.

Hash and Multihash arbitrary

---

benches/multihash.rs
src/digests.rs
src/hashes.rs
tests/hashes.rs
tests/lib.rs

This PR does the following:
- extends `MultihashDigest` with an `input` and `result` method (borrowed from the `Digest` and `Input` traits) to support streaming
- implements the new methods for all existing codecs
- this required changing their implementation to embed the existing digest, but the `impl Default` makes hasher construction easy
- drastically reduces the amount of repetition in the `impl Code` and `impl MultihashDigest`s using two local macros.
- replaces `Code::to_u64` and `Code::from_u64` with `From<Code> for u64` and `From<u64> for Code`
All the original tests still pass and the core API is mostly the same (with the exception of hasher construction) ideally satisfying the O in SOLID :grin: 
Let me know what y'all think!

WIP streaming support, macro refactor

---

src/arb.rs
src/digests.rs
src/hashes.rs
src/lib.rs
tests/hashes.rs
tests/lib.rs

With generics it is now possible to have your own code tables. Most users
won't need those, hence there are type aliases to make this library easy
to use with the default case.
This doesn't commit doesn't change the API of `Multihash` or `MultihashRef`,
but the `MultihashDigest` trait now needs a generic type, usually
`MultihashDigest<Code>`.
BREAKING CHANGE: `MultihashDigest` needs a generic now
If you have used `MultihashDigest` you now need to use it as `MultihashDigest<Code>`.

 feat: use generics for custom code tables

---

src/arb.rs
src/digests.rs
src/hashes.rs
src/lib.rs
tests/hashes.rs

BREAKING CHANGE: Instead of calling `hasher()` use `from()` instead
Prior to this change, your code looked like this:
let hasher = Code::Sha3_512.hasher();
Now it is:
let hasher = Box::<dyn MultihashDigest<Code>>::from(Code::Sha3_512);
I tend to use the (Try)From trait everywhere these days, so please be critical if it doesn't make sense (though in this case I really like it).

feat: implement `hasher()` as `From` to `MultihashDigest<Code>`

---

src/digests.rs

The only reason these bounds are necessary are because in `MultihashRefGeneric::algorithm`, `expect` requires it - however, because the error should never even occur, it shouldn't really matter what error we panic with so long as its not completely useless, and thus the method doesn't need to require these bounds.
I've correspondingly opened a PR [1] in rust-cid to remove those unnecessary bounds from the `CidGeneric` type.
[1] See https://github.com/multiformats/rust-cid/pull/60 for the full consequences of the change.

remove unnecessary TryFrom error bounds

---

src/digests.rs
tests/lib.rs

When a Multihash is created, we make sure that the supplied code is supported,
hence part of the code table. Throw an error if a passed in multihash contains
an unsupported code.
Fixes #70.

fix: make sure Multihashes are always valid

---

src/digests.rs

The example just illustrates different uses without being a proper
fully working example, hence don't compile or test it.
Fixes #75.

chore: fix code example

---

Cargo.toml
src/digests.rs
src/hashes.rs

~~**BREAKING CHANGE**: Rename some methods in the `MultihashDigest` trait~~
~~`input` ==> `update`~~
~~`result` ==> `finalize`~~
~~`result_reset` ==> `finalize_reset`~~

feat: update digest, sha-1, sha2 and sha3 to v0.9

---

src/multihash.rs

https://github.com/multiformats/rust-multihash/commit/7a6933731e3cb8dcbd086668dc2375bccb337d1a
introduced order of multihashes. That got lost during the most recent
merge. This commit revives it again.

fix: revive ordering of multihashes.

---

derive/src/lib.rs
derive/src/multihash.rs
examples/custom_table.rs
src/arb.rs
src/lib.rs
src/multihash.rs
src/multihash_impl.rs
tests/lib.rs

While I was looking into upgrading libp2p to this version of multihash,
I realized that `MultihashCode` might not be such a good name for the
trait.
First of all, it's kind of a meaningless name. What does it actually do?
It does create digests, hence I think `MultihashDigest` is a better name.
Also `MultihashCode` can easily clash with other names. For example if
you have a custom Multihash code table, just calling it `Code` might be
a to generic name in case you want to have it as a top-level export. Then
`MultihashCode` might be a good name, but it would clash with the trait
name.
BREAKING CHANGE: The `MultihashCode` trait is now named `MultihashDigest`.

feat: rename MultihashCode to MultihashDigest

---

src/lib.rs
src/multihash_impl.rs

The `multihash-impl` feature enables all hashers, so there is no point
of checking if a hasher is enabled. If the `multihash-impl` feature is
disabled, the whole module won't be included.

docs: clarify multihash-impl feature

---

src/arb.rs

The `arb` module was using `std::Vec` which isn't no_std compatible.

fix: make arb feature no_std compatible

---

.github/workflows/build.yml
Cargo.toml
src/lib.rs
src/multihash_impl.rs

It is now possible to change the contents of the default code table
with enabling/disabling various features. If you e.g. only need SHA2
hashes, you can specify that when you use the `multihash` dependency:
multihash = {
version = …,
default-features = false,
features = ["std", "multihash-impl", "sha2"]
}
BREAKING CHANGE: Only secure hashers are enabled by default

feat: default code table can be changed at compile time

---

derive/src/lib.rs
derive/src/multihash.rs
examples/custom_table.rs
src/arb.rs
src/lib.rs
src/multihash.rs
tests/lib.rs

Instead of only export the `Multihash` that is generic over the allocated
size, also expose `Multihash` that is created by the `Multihash` derive.
If the `multihash-impl` feature is enabled, also a `Multihash` with the
corresponding size gets exported.
BREAKING CHANGE: The `Multihash` which is generic over the size is now
called `MultihashGeneric`.

feat: create Multihash that matches the code table

---

derive/src/multihash.rs

@vmx please merge and release 0.13.2, this is blocking a new libipld release

Support building multihash with no hashes enabled.

---

derive/src/multihash.rs
src/hasher.rs
src/hasher_impl.rs
src/lib.rs
tests/lib.rs

Instead of having a (non-working) wrapper struct for implementing
std::io::Write for a hasher, implement it directly on the hasher
instead.
Closes #95.
@dvc94ch you implemented the original `WriteHasher` wrapper. Is there a reason to do it that way or was it just a different code base and this PR is a better implementation?

feat: implement std::io::Write trait for the hashers

---

derive/src/multihash.rs
src/multihash_impl.rs

There are additional clippy warning on Rust 1.51. This commit fixes
those.

chore: fix clippy warning on latest stable

---

src/lib.rs
src/multihash.rs

~~waiting for #139 to be merged firstly~~
This PR is a breaking change.
**BREAKING CHANGE**: Write the digest of multihash directly to dest when encoding multihash, since we have known the size of digest.
We do not choose to encode &[u8] directly, because it will add extra bytes
(the compact length of digest) at the beinging of encoding result.
For a valid multihash, the length of digest must equal to `size` field of multihash.
Therefore, we can only read raw bytes whose length is equal to `size` when decoding.
And the digest of Multihash\<U64\> is of type [u8; 64], taking Code::Sha2_256 as an example,
if the digest is treated as &[u8] when encoding, useless data will be added to
the encoding result.

Fix scale-codec for `Multihash`

---

src/multihash.rs

TODO: should _truncate_ mutate or return a new object? Currently, I'm returning a new object.

Support multihash resizing

---

Cargo.lock
Cargo.toml

Also makes core2 alloc feature optional

Enable cargo test without command line arguments

---

Cargo.lock
Cargo.toml
README.md
derive/src/lib.rs
derive/src/multihash.rs
examples/custom_table.rs
src/arb.rs
src/hasher.rs
src/hasher_impl.rs
src/lib.rs
src/multihash.rs
src/multihash_impl.rs
tests/lib.rs

I'm usually a fan of having a clean Git history. Though in this case I think we want all the changes from the `next` branch to land on master. Also all changes were reviewed before they were merged into the `next` branch. So I'm in favour of merging the `next` branch into `master` now.
There are still two PRs open that I think make sense to land before we cut a release (they probably need to be polished a bit more). But this can be done after this one is merged.
It would be great if everyone involved (@dignifiedquire, @mriise, @samuelburnham, @Stebalien) in the changes could give a thumbs up for this PR to land on `master`. (as it really is a lot of (breaking) changes, most notably @mriise excellent long running effort on making const generics work).

Several improvements

---

README.md
benches/multihash.rs
derive/src/lib.rs
derive/src/multihash.rs
examples/custom_table.rs
src/hasher.rs
src/hasher_impl.rs
src/lib.rs
src/multihash.rs
src/multihash_impl.rs
tests/lib.rs

Remove the per-hasher digest type. Instead, store hash digests inside the hashers and "borrow" it. In all cases, we're going to copy it into a `Multihash<S>` anyways.
This:
1. Removes bunch of code.
2. Means that hashers don't need to be generic over the size (unless they actually support multiple sizes). This fixes the UX issue introduced in the const generics PR.
3. Avoids some copying.
BREAKING CHANGE
1. `Hasher.digest` no longer exists. Users should use `Code::SomeCode.digest` where possible.
2. The hasher digests no longer exist.
TODO: Do we want this? From what I can tell, most users won't really be impacted by it.

remove per-hash digest type

---

Cargo.lock
Cargo.toml
src/arb.rs

arbitrary::Arbitrary is a trait used for generation of arbitrary values
of structs used for fuzzing.
It differes from the quickcheck::Arbitrary by sourcing from a buffer
instead of Rng.

Add Arbitrary implementation used for fuzzing

---

.github/workflows/build.yml

`cargo fmt` fmt prints warnings, but doesn't lead to failures.
This reverts commit 6235d260e7e95a51fdf697940fda0b02eb9e9434.

revert: Revert "skip fmt on stable"

---

Cargo.toml

The crate was already using resolver v2, hence it makes sense to upgrade to Rust edition 2021, which implicitly uses that resolver.
Also set the minimum required Rust version to 1.59 due to the `constant_time_eq` dependency.
BREAKING CHANGE: update to Rust edition 2021
---
I thought as we do a breaking release, we might as well upgrade the rust edition.

fix: update to Rust edition 2021

---

CHANGELOG.md
RELEASE.md

This commit prepares a new release. It also documents the release process. Thanks iroh team for letting me copy the process.
I plan to do a 0.18 release tomorrow. Please raise any objections if you have any.

chore: add v0.18 changelog

---

.gitignore
RELEASE.md

Those are just minor things that don't even need a changelog entry. Last changes before doing the 0.18 release.

Two small cleanups before the release

---

tests/lib.rs

Rust 1.66 lead to a new Clippy warning, this commit fixes it in order to get CI back to green.

chore: fix Clippy warning

---

.github/workflows/build.yml
deny.toml

1. Locks the list of allowed licenses to the current set of dependency licenses
2. Surfaces two advisories as warnings (comments added to `deny.yml` for both)
3. Surfaces duplicate versions of the same dependency as warnings (comments added to `deny.yml` for both)
One of the advisories is for `atty` a dependency of `criterion` and tracked in an [issue in the criterion repo](https://github.com/bheisler/criterion.rs/pull/628).

Add cargo deny to CI

---

.github/workflows/build.yml

This PR fixes the coverage job by switching to the tarpaulin docker container from the (unmaintained) Github action.

fix(ci): switch to tarpaulin docker image

---

src/error.rs
src/multihash.rs

If a varint it non-minimally encoded in a no_std environment, don't panic, but return an error.
Fixes #282.

fix: don't panic on non minimal varints

---

Cargo.toml
src/lib.rs
src/multihash.rs
src/serde.rs

Multihash has a defined bytes representation, serialize it as such one instead of deriving it from the internal representation. This way there is no leak of internal implementation details.
BREAKING CHANGE: The Serde serialization format changed

feat: Serde serialize Multihash in bytes representation

---

codetable/src/lib.rs

Can't use any methods without exposing the trait implemented from deriving.
e.g. `Code::try_from(0x12).digest(&[0xb0, 0xba])`

Expose `MultihashDigest` trait in codetable

---

codetable/Cargo.toml
codetable/src/hasher_impl.rs
codetable/src/lib.rs
codetable/tests/lib.rs
derive/Cargo.toml
derive/tests/pass/derive.rs
examples/identity.rs

This itself is not a breaking changes because `multihash-codetable` isn't released yet. We add an example to `multihash` on how to do identity hashing.
Resolves #194.
Replaces #196.
Replaces #201.
Replaces #260.

feat(codetable): remove `identity` hasher

---

CHANGELOG.md
RELEASE.md

Make it clearer that the changelog is the place for explaining migrations.
Also change the changelog from angular to the conventionalcommits style as mentioned at
https://github.com/multiformats/rust-multihash/pull/276#issuecomment-1479206358.

chore: update release instructions

---

.github/workflows/build.yml
README.md

We only activate `std` by default and don't use any very recent std features. Other features will bring in dependencies where we don't control the MSRV policy. Thus, we don't guarantee a MSRV with features activated.
Resolves #317.

feat: don't activate features for MSRV check

---

CHANGELOG.md

This sits at the top of the changelog for now. Once we do the release, we can just copy the generated changelog notes on top of it and it will become the last section of the `v0.19` release section.

docs: add migration section

---

README.md

Currently, the README is terribly outdated. It will likely get outdated again because the code samples in there are not type-checked.
This should do for now and hopefully unblock the `v0.19` release.

docs: make README not terribly outdated

---

.github/workflows/build.yml
codetable/Cargo.toml
src/serde.rs

`multihash` v0.19 introduced a regression. It's no longer possible to compile with `no_std` and `serde` feature enabled. This commit fixes that regression.
Due to generic_const_exprs not being a thing yet, we need to use unsafe code to provide this functionality.
Fixes #336.

fix: make Serde (de)serialization no_std compatible

---

codetable/src/hasher_impl.rs

In the refactor where each hasher was moved to a separate feature, the conditional compilation of derive_write! was written such that enabling only blake2 hashing will result in compilation errors:
error: cannot find macro `derive_write` in this scope
--> /home/cyphar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/multihash-codetable-0.1.0/src/hasher_impl.rs:59:9
|
59 |         derive_write!($name);
|         ^^^^^^^^^^^^
...
65 |     derive_hasher_blake!(blake2b_simd, Blake2bHasher);
|     ------------------------------------------------- in this macro invocation
|
= note: this error originates in the macro `derive_hasher_blake` (in Nightly builds, run with -Z macro-backtrace for more info)
error: could not compile `multihash-codetable` (lib) due to previous error
Fixes: …

codetable: fix build for blake2s and blake2b features

---

codetable/Cargo.toml
codetable/src/lib.rs

This change affects only builds on docs.rs. Previously docs.rs built
multihash-codetable with only the default features enabled, thus all
the content of the crate could be inspected only when reading sources.
This change exposes all items from the crate on docs.rs and labels
them with what features they require.

docs(codetable): expose all items with required features on docs.rs

---

.github/workflows/build.yml
derive-impl/Cargo.toml
derive-impl/src/multihash.rs
derive-impl/src/utils.rs
derive/tests/fail/no_allow_same_code_twice.stderr
derive/tests/fail/no_allow_same_name_twice.stderr

fixes #362
closes #350 
closes #301 
* I've added an `Ident` to `utils::Attrs` since `attr.meta.to_token_stream()` now includes it.
* I've also removed `ParseError` since it didn't seem to be used (and tests seemed to passed)

fix: upgrade syn and synstructure (#362)

---

derive-impl/src/utils.rs

There are some attributes which aren't used yet. Include them though, as they are parsed anyway.
Also communicate clearer that the attribute types are not part of the public interface, but only used internally.

fix: fix Clippy warnings

---

codetable/Cargo.toml
codetable/src/lib.rs

I found myself writing a newtype wrapper over `Code` to get an `impl proptest::Arbitrary`, and thought "hey, why don't I upstream this one-liner?"
I tried to keep to your libraries and conventions as much as possible (e.g. `arb`), but please let me know if I missed anything.
(Some of the automated checks are failing, but I'm 90% sure those failures "shouldn't" be related to this change. It's late here, so I'll double check tomorrow)

Derive `Arbitrary` for `multihash_codetable::Code`

---

.github/workflows/build.yml
codetable/Cargo.toml
codetable/src/hasher_impl.rs
codetable/src/lib.rs
deny.toml
derive-impl/Cargo.toml
derive-impl/src/lib.rs
derive-impl/src/multihash.rs
derive/tests/fail/no_allow_same_code_twice.stderr
derive/tests/fail/no_allow_same_name_twice.stderr

We can already emit errors directly with `syn`, so we can just drop this dependency entirely.

fix: remove the unmaintained proc-macro-error dependency

---

.github/workflows/build.yml

Only enabling the `arb` feature on the `codetable` crate now fails, due to changes to the `arbitrary_derive` crate. It now errors if the enum its derived from is empty. Which it is in our case.

chore: fix CI

---

Cargo.toml

During the refactor at 954e5233d273a2b7d682fd087178203628d131a4 the ability to compile the `multihash` crate with `alloc` but without `std` was lost. Now it works again.
Fixes #375.
The CI failure on the codetable is unrelated and has a fix at #376.

fix: make alloc without std work

---

.github/workflows/build.yml
derive/tests/fail/no_allow_same_code_twice.stderr
derive/tests/fail/no_allow_same_name_twice.stderr

The error messages changed slightly, hence update them.
Also a newer version of Tarpaulin is needed, so that it also uses those newer error messages.

test: update error message
